objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <description>Tracks the location of the Account Owner</description>
        <label>Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Account_Region__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APAC</fullName>
                    <label>APAC Other</label>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>DACH</fullName>
                </value>
                <value>
                    <fullName>East Asia</fullName>
                </value>
                <value>
                    <fullName>FraBeLux</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>LATAM Other</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>Middle East &amp; Africa</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>Russia</fullName>
                </value>
                <value>
                    <fullName>SEA</fullName>
                </value>
                <value>
                    <fullName>SE Europe &amp; CIS</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>US East</fullName>
                </value>
                <value>
                    <fullName>US West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <description>SaaS</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <businessProcess>SaaS</businessProcess>
        <description>SaaS Sales</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <description>This field categorizes products by license type. Products that are not specific to license type are categorized as Platform.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recommend</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Find</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ClonedOpportunityControllerTest.cls
@isTest
public class ClonedOpportunityControllerTest {
	@isTest
	public static void testClonedOpportunity()
    {
        Account act = new Account(Name='Test Account', Sub_Region__c = 'UK');
        insert act;
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId=act.Id, StageName='(SaaS) RR on short list - 60%', CloseDate=Date.today());
        insert opp;
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(Name='test Prodcut', ProductCode='Pro-X', isActive=true, Family = 'License', Product_Sub_Category__c ='Recommend ');
        insert prod;
        PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id=pricebookId, Product2Id=prod.Id, UnitPrice=100.00, IsActive=true);
        insert pbEntry;
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId=opp.Id, Quantity=5, PricebookEntryId=pbEntry.Id);
        insert oli;
        apexPages.currentPage().getparameters().put('id' , opp.Id);
        apexPages.currentPage().getparameters().put('clonePro' , '1');
        CloneOpportunityController coc = new CloneOpportunityController(null);
		coc.jumpToEdit();
    }
}