objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <description>SaaS</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Sales and Customer Contacts</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <businessProcess>SaaS Sales</businessProcess>
        <description>SaaS Lead Process</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Mobile_Addressable__c</fullName>
        <description>Percent of revenue through the Mobile Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</description>
        <inlineHelpText>Percent of revenue through the Mobile Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</inlineHelpText>
        <label>Mobile % Addressable</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Mobile_Revenue__c</fullName>
        <description>Revenue that company attributes as coming through it&apos;s Mobile Channel.  Mobile is defined as Mobile App, Mobile Device (Phone, Tablet, Smart Watch, etc.)</description>
        <inlineHelpText>Revenue that company attributes as coming through it&apos;s Mobile Channel.  Mobile is defined as Mobile App, Mobile Device (Phone, Tablet, Smart Watch, etc.)</inlineHelpText>
        <label>Mobile Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberOfSites__c</fullName>
        <defaultValue>1</defaultValue>
        <label># of Sites</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Web_Online_Perc_Addressable__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Percent of revenue through the Computer (Online) Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</description>
        <inlineHelpText>Percent of revenue through the Computer (Online) Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</inlineHelpText>
        <label>Web (Online) % Addressable</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Web_Online_Revenue__c</fullName>
        <description>Formerly known as Online Revenue.  Upon creation of a new opportunity, this is copied from the information on the account level and can be overridden.</description>
        <inlineHelpText>Formerly known as Online Revenue.  Upon creation of a new opportunity, this is copied from the information on the account level and can be overridden.</inlineHelpText>
        <label>Web (Online) Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <businessProcess>SaaS</businessProcess>
        <description>SaaS Sales</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Integration_Rate__c</fullName>
        <description>The hourly rate for integration services.</description>
        <inlineHelpText>Enter the rate per hour for integration service products.</inlineHelpText>
        <label>Integration Rate</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductSubFamily__c</fullName>
        <label>Product Add-On</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CNET DataSource</fullName>
                </value>
                <value>
                    <fullName>BYOS</fullName>
                </value>
                <value>
                    <fullName>BYO-API</fullName>
                </value>
                <value>
                    <fullName>Monthly API</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 1</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 2</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 3</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 4</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <description>This field categorizes products by license type. Products that are not specific to license type are categorized as Platform.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recommend</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Find</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UseStandardPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The price defined on the standard price book for this product will be used when it&apos;s checked.</inlineHelpText>
        <label>Use Standard Price</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SendQuoteExtensionTest.cls
@isTest
private class SendQuoteExtensionTest 
{   
    @isTest 
    static void testSendQuoteExtension() 
    {
        /* Create Test Data */
        Account newAccount = TestDataFactory.createAccount('Test Account');
        Database.insert(newAccount, false);

        Contact newContact = 
            TestDataFactory.createContact(newAccount.Id, 'Test', 'Contact', 'test@acme.com');
        Database.insert(newContact, false);

        Opportunity newOpp = 
            TestDataFactory.createOpportunity(newAccount.Id, 'Test Opportunity', '(SaaS) Lead - 10%', Date.today().addMonths(1), 'EUR');
            newOpp.Web_Online_Revenue__c = 2000000;
            newOpp.Web_Online_Perc_Addressable__c = 100;
            newOpp.Mobile_Revenue__c = 2000000;
            newOpp.Mobile_Addressable__c = 100;
            newOpp.NumberOfSites__c = 2;
        Database.insert(newOpp, false);

        Product2 newProd1 = TestDataFactory.createProduct('Lincese-Recommend', 'License-Recommend', true);
        newProd1.Family = 'License';
        newProd1.Product_Sub_Category__c = 'Recommend';

        Product2 newProd2 = TestDataFactory.createProduct('License-Recommend-BYOS', 'License-Recommend-BYOS', true);
        newProd2.Family = 'License';
        newProd2.Product_Sub_Category__c = 'Recommend';        
        newProd2.ProductSubFamily__c = 'BYOS';

        Product2 newProd3 = TestDataFactory.createProduct('Use Standard Price', 'Use Standard Price', true);
        newProd3.Family = 'License';
        newProd3.Product_Sub_Category__c = 'Legacy';
        newProd3.UseStandardPrice__c = true;


        Product2 newProd4 = TestDataFactory.createProduct('Services', 'Services', true);
        newProd4.Family = 'Service';
        newProd4.Product_Sub_Category__c = 'Platform';
        newProd4.Integration_Rate__c = 100;
        newProd4.Hours__c = 100;

        Product2 newProd5 = TestDataFactory.createProduct('Integration', 'Integration', true);
        newProd5.Family = 'Integration';
        newProd5.Product_Sub_Category__c = 'Recommend';
        newProd5.Integration_Rate__c = 100;
        newProd5.Hours__c = 100;

        List<Product2> newProducts = new List<Product2>{newProd1, newProd2, newProd3, newProd4, newProd5};                
        Database.insert(newProducts, false);

        String standardPricebookId = Test.getStandardPricebookId();        
        
        List<PricebookEntry> entries = new List<PricebookEntry>();
        entries.add(TestDataFactory.createPricebookEntry(newProd1.Id, standardPricebookId, 'EUR', 100, true));
        entries.add(TestDataFactory.createPricebookEntry(newProd2.Id, standardPricebookId, 'EUR', 100, true));
        entries.add(TestDataFactory.createPricebookEntry(newProd3.Id, standardPricebookId, 'EUR', 100, true));
        entries.add(TestDataFactory.createPricebookEntry(newProd4.Id, standardPricebookId, 'EUR', 100, true));        
        entries.add(TestDataFactory.createPricebookEntry(newProd5.Id, standardPricebookId, 'EUR', 100, true));        
        Database.insert(entries, false); 

        List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>();
        lineItems.add(TestDataFactory.addProduct2Opportunity(newOpp.Id, entries[0].Id, 100, 1, 0));
        lineItems.add(TestDataFactory.addProduct2Opportunity(newOpp.Id, entries[1].Id, 100, 1, 0));
        lineItems.add(TestDataFactory.addProduct2Opportunity(newOpp.Id, entries[2].Id, 100, 1, 0));
        lineItems.add(TestDataFactory.addProduct2Opportunity(newOpp.Id, entries[3].Id, 100, 1, 0));
        lineItems.add(TestDataFactory.addProduct2Opportunity(newOpp.Id, entries[4].Id, 100, 1, 0));
        Database.insert(lineItems, false);

        newOpp = [select Id, Name, Pricebook2Id, SyncedQuoteID from Opportunity where Id = :newOpp.Id];
        Quote newQuote = TestDataFactory.createQuoteFromOpportunity(newOpp, lineItems);

        newOpp.SyncedQuoteID = newQuote.Id;
        update newOpp;
        /* Create Test Date End */  

        Test.startTest();

        ApexPages.StandardController stdController = new ApexPages.StandardController(newOpp);
        SendQuoteExtension extension = new SendQuoteExtension(stdController);

        extension.PrimaryQuote.ContactId = newContact.Id;
        extension.TempQuote.ContactId = newContact.Id;
        extension.Email.CCAddr = 'test2@acme.com';
        extension.Email.Body = 'Email Body';
        extension.send();
        
        Test.stopTest();    
    }   
}