objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <description>SaaS</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Sales and Customer Contacts</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <businessProcess>SaaS Sales</businessProcess>
        <description>SaaS Lead Process</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Mobile_Addressable__c</fullName>
        <description>Percent of revenue through the Mobile Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</description>
        <inlineHelpText>Percent of revenue through the Mobile Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</inlineHelpText>
        <label>Mobile % Addressable</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Mobile_Revenue__c</fullName>
        <description>Revenue that company attributes as coming through it&apos;s Mobile Channel.  Mobile is defined as Mobile App, Mobile Device (Phone, Tablet, Smart Watch, etc.)</description>
        <inlineHelpText>Revenue that company attributes as coming through it&apos;s Mobile Channel.  Mobile is defined as Mobile App, Mobile Device (Phone, Tablet, Smart Watch, etc.)</inlineHelpText>
        <label>Mobile Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NumberOfSites__c</fullName>
        <defaultValue>1</defaultValue>
        <label># of Sites</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Web_Online_Perc_Addressable__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Percent of revenue through the Computer (Online) Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</description>
        <inlineHelpText>Percent of revenue through the Computer (Online) Channel that can be addressed by RichRelevance products.  Negotiated with the customer.  Enter as a number and percentage will be assigned.</inlineHelpText>
        <label>Web (Online) % Addressable</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Web_Online_Revenue__c</fullName>
        <description>Formerly known as Online Revenue.  Upon creation of a new opportunity, this is copied from the information on the account level and can be overridden.</description>
        <inlineHelpText>Formerly known as Online Revenue.  Upon creation of a new opportunity, this is copied from the information on the account level and can be overridden.</inlineHelpText>
        <label>Web (Online) Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>SaaS</fullName>
        <active>true</active>
        <businessProcess>SaaS</businessProcess>
        <description>SaaS Sales</description>
        <label>SaaS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CSDirector__c</fullName>
        <description>Indicates the client services director that should be copied on the 1st level approval email message for opportunities.</description>
        <label>CS Director</label>
        <relationshipName>CSDirector</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TriggerTestUtils.cls
@isTest
public class TriggerTestUtils 
{
    @isTest
    static void testUserTrigger()
    {
        /* Create Test Data */
        Account newAccount = TestDataFactory.createAccount('Test Account');
        Database.insert(newAccount, false);

        Contact newContact = 
            TestDataFactory.createContact(newAccount.Id, 'Test', 'Contact', 'test@acme.com');
        Database.insert(newContact, false);

        Opportunity newOpp = 
            TestDataFactory.createOpportunity(newAccount.Id, 'Test Opportunity', '(SaaS) Lead - 10%', Date.today().addMonths(1), 'EUR');
            newOpp.Web_Online_Revenue__c = 2000000;
            newOpp.Web_Online_Perc_Addressable__c = 100;
            newOpp.Mobile_Revenue__c = 2000000;
            newOpp.Mobile_Addressable__c = 100;
            newOpp.NumberOfSites__c = 2;
        Database.insert(newOpp, false);

        User currentUser = [select CSDirector__c from User where Id = :UserInfo.getUserId()];
        Database.update(currentUser, false);

        List<User> users = [select Id from User where UserType = 'Standard' and IsActive = true and CSDirector__c = null limit 1];
        if(users.size() > 0)
        {
            currentUser.CSDirector__c = users[0].Id;
        }        
        Database.update(currentUser, false);        
    }


    @isTest
    static void testTaskTrigger()
    {
        /* Create Test Data */
        Account newAccount = TestDataFactory.createAccount('Test Account');
        Database.insert(newAccount, false);

        Contact newContact = 
            TestDataFactory.createContact(newAccount.Id, 'Test', 'Contact', 'test@acme.com');
        Database.insert(newContact, false);

        Opportunity newOpp = 
            TestDataFactory.createOpportunity(newAccount.Id, 'Test Opportunity', '(SaaS) Lead - 10%', Date.today().addMonths(1), 'EUR');
            newOpp.Web_Online_Revenue__c = 2000000;
            newOpp.Web_Online_Perc_Addressable__c = 100;
            newOpp.Mobile_Revenue__c = 2000000;
            newOpp.Mobile_Addressable__c = 100;
            newOpp.NumberOfSites__c = 2;
        Database.insert(newOpp, false);

        Attachment newAttachment = new Attachment(Name = 'Test.pdf', ParentId = newOpp.Id);
        newAttachment.Body = Blob.valueOf('Test');
        Database.insert(newAttachment, false);

        Task closedTask = new Task(OwnerId = UserInfo.getUserId(), WhatId = newOpp.Id);
        closedTask.Subject = 'Email: Test';
        closedTask.Status = 'Completed';
        closedTask.ActivityDate = Date.today();
        closedTask.Priority = 'Normal';
        closedTask.Type = 'Email';
        Database.insert(closedTask, false);
    }
}