objects/BasePriceTable__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>PriceCap__c</fullName>
        <label>Price Cap</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TierCostPercent__c</fullName>
        <label>Tier Cost %</label>
        <precision>6</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TierPriceEnd__c</fullName>
        <label>Tier Price End</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TierPriceStart__c</fullName>
        <label>Tier Price Start</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BasePriceTable</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF(Total_List_Price__c == 0, 0, 1-Amount/Total_List_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NumberOfSites__c</fullName>
        <defaultValue>1</defaultValue>
        <label># of Sites</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Addressable_Revenue__c</fullName>
        <description>This field is a sum of Web (Online), Mobile, Phone, and In-Store Addressable Revenue.</description>
        <formula>Total_Addressable_Web_Online_Rev__c + Total_Addressable_Mobile_Rev__c + Total_Addressable_Phone_Con_Ctr_Rev__c + Total_Addressable_In_Store_Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is a sum of Web (Online), Mobile, Phone, and In-Store Addressable Revenue.  This field should be entered into the pricing calculator.</inlineHelpText>
        <label>Total Addressable Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hours_Info_Only__c</fullName>
        <description>Number of Hours for a services Engagement. This is not a calculated field, but used to capture hours for informational purposes.</description>
        <inlineHelpText>Number of Hours for a services Engagement. This is not a calculated field, but used to capture hours for informational purposes.</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <description>Custom list price for Sales folks to enter</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Integration_Rate__c</fullName>
        <description>The hourly rate for integration services.</description>
        <inlineHelpText>Enter the rate per hour for integration service products.</inlineHelpText>
        <label>Integration Rate</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductSubFamily__c</fullName>
        <label>Product Add-On</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CNET DataSource</fullName>
                </value>
                <value>
                    <fullName>BYOS</fullName>
                </value>
                <value>
                    <fullName>BYO-API</fullName>
                </value>
                <value>
                    <fullName>Monthly API</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 1</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 2</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 3</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 4</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <description>This field categorizes products by license type. Products that are not specific to license type are categorized as Platform.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recommend</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Find</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UseStandardPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The price defined on the standard price book for this product will be used when it&apos;s checked.</inlineHelpText>
        <label>Use Standard Price</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductPriceTable__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BundleDiscount__c</fullName>
        <label>Bundle Discount</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PercentOfBase__c</fullName>
        <label>% of Base</label>
        <precision>5</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ProductPriceTable</label>
</CustomObject>

classes/PriceCalculator.cls
public with sharing class PriceCalculator
{
    private static List<BasePriceTable__c> basePriceSettings;
    private static Map<String, ProductPriceTable__c> productPriceMap;


    public static void calculatePrice(Opportunity opp, List<OpportunityLineItem> lineItems)
    {
        for(OpportunityLineItem lineItem : lineItems)
        {
            lineItem.List_Price__c = calculateListPrice(opp, lineItem);
            if(lineItem.UnitPrice == null)
            {
                lineItem.UnitPrice = lineItem.List_Price__c;
            }
            /*
            if(lineItem.Discount__c == null)
            {
                lineItem.Discount__c = 0.00;
            }
            lineItem.UnitPrice = calculateUnitPrice(lineItem);
            */
            lineItem.Discount__c = calculateDiscount(lineItem);
        }
    } 

    private static Decimal calculateListPrice(Opportunity opp, OpportunityLineItem lineItem)
    {
        if(lineItem.PricebookEntry.Product2.UseStandardPrice__c)
        {
            return lineItem.Hours_Info_Only__c == null ? 0.00 : lineItem.PricebookEntry.UnitPrice * lineItem.Hours_Info_Only__c;
        }
        if(lineItem.PricebookEntry.Product2.Family == 'Services')
        {
            return getServiceProductPrice(opp, lineItem);
        }       
        if(lineItem.PricebookEntry.Product2.Family == 'Integration')
        {
            return getIntegrationProductPrice(opp, lineItem);
        } 
        if(lineItem.PricebookEntry.Product2.Family == 'License')
        {
            return getLicenseProductPrice(opp, lineItem);
        }
        return 0.00;
    }

    private static Decimal getServiceProductPrice(Opportunity opp, OpportunityLineItem lineItem)
    {        
        Decimal hours = lineItem.Hours_Info_Only__c;
        Decimal rates = lineItem.PricebookEntry.Product2.Integration_Rate__c;
        if(hours == null || hours == 0)
        {
            return 0.00;
        }
        if(rates == null || rates == 0)
        {
            return 0.00;
        }          
        Decimal price = rates * hours;
        return (CurrencyConversion.convertToLocalCurrency(price, opp.CurrencyIsoCode)).setScale(2);
    }

    private static Decimal getIntegrationProductPrice(Opportunity opp, OpportunityLineItem lineItem)
    {
        Decimal hours = lineItem.Hours_Info_Only__c;
        Decimal rates = lineItem.PricebookEntry.Product2.Integration_Rate__c;
        if(hours == null || hours == 0)
        {
            return 0.00;
        }
        if(rates == null || rates == 0)
        {
            return 0.00;
        }

        
        // Based on Julie's response on 10/18/2016, the NumberofSites should not be included in the pricing calculation.
        /*
        if(opp.NumberOfSites__c == null || opp.NumberOfSites__c == 0)
        {
            return 0.00;
        }   
        Decimal price = rates * hours + rates * hours * (opp.NumberOfSites__c - 1) * 0.8;
        return (CurrencyConversion.convertToLocalCurrency(price, opp.CurrencyIsoCode)).setScale(2);  
        */ 

        Decimal price = rates * hours;
        return (CurrencyConversion.convertToLocalCurrency(price, opp.CurrencyIsoCode)).setScale(2);

             
    }

    private static Decimal getLicenseProductPrice(Opportunity opp, OpportunityLineItem lineItem)
    {
        if(productPriceMap == null)
        {
            initProductPriceMap();
        }
        String key = null;        
        if(productPriceMap.containsKey(lineItem.PricebookEntry.Product2.ProductSubFamily__c))
        {
            key = lineItem.PricebookEntry.Product2.ProductSubFamily__c;
        }
        else if(productPriceMap.containsKey(lineItem.PricebookEntry.Product2.Product_Sub_Category__c))
        {
            key = lineItem.PricebookEntry.Product2.Product_Sub_Category__c;
        }

        if(key != null)
        {
            Decimal basePricePercent = productPriceMap.get(key).PercentOfBase__c;
            Decimal bundleDiscount = productPriceMap.get(key).BundleDiscount__c; 
            if(basePricePercent == null)
            {
                basePricePercent = 1;
            }
            if(bundleDiscount == null)
            {
                bundleDiscount = 1;
            }
            Decimal price = getBasePrice(opp) * basePricePercent * bundleDiscount;
            return (CurrencyConversion.convertToLocalCurrency(price, opp.CurrencyIsoCode)).setScale(2);
        }
        return 0.00;
    }

    private static void initProductPriceMap()
    {
        productPriceMap = new Map<String, ProductPriceTable__c>();
        List<ProductPriceTable__c> productPriceSettings = ProductPriceTable__c.getAll().values();
        for(ProductPriceTable__c productPrice : productPriceSettings)
        {
            productPriceMap.put(productPrice.ProductFamily__c, productPrice);
        }
    }

    private static Decimal getBasePrice(Opportunity opp)
    {        
        Decimal totalRevenue = CurrencyConversion.convertToCorpCurrency(opp.Total_Addressable_Revenue__c, opp.CurrencyIsoCode);
        if(totalRevenue == null)
        {
            totalRevenue = 0;
        }

        Decimal basePrice = 0.00;
        if(basePriceSettings == null)
        {
            initBasePriceSettings();
        }
        for(BasePriceTable__c setting : basePriceSettings)
        {
            if((totalRevenue >= setting.TierPriceStart__c || setting.TierPriceStart__c == null)
            && (totalRevenue <= setting.TierPriceEnd__c || setting.TierPriceEnd__c == null))
            {
                if(setting.TierCostPercent__c == null)
                {
                    basePrice = totalRevenue;
                }
                else
                {
                    basePrice = totalRevenue * setting.TierCostPercent__c;
                }   
                if(setting.PriceCap__c == null || setting.PriceCap__c > basePrice)
                {
                    return basePrice;
                }             
                else
                {
                    return setting.PriceCap__c;
                }
            }
        }
        return basePrice;
    }

    private static void initBasePriceSettings()
    {
        Map<String, BasePriceTable__c> basePriceMap = BasePriceTable__c.getAll();
        basePriceSettings = basePriceMap.values();
    }
    /*
    private static Decimal calculateUnitPrice(OpportunityLineItem lineItem)
    {        
        if(lineItem.Discount__c == 100)
        {
            return 0;
        }
        return (lineItem.List_Price__c * (1 - lineItem.Discount__c / 100)).setScale(2);
    }
    */
    private static Decimal calculateDiscount(OpportunityLineItem lineItem)
    {        
        if(lineItem.List_Price__c == 0)
        {
            return 0;
        }
        return (100 * (1 - lineItem.UnitPrice / lineItem.List_Price__c)).setScale(2);
    }
}