objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Sales and Customer Contacts</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Build__c</fullName>
        <formula>IF(Build_Subscription_Fee__c&gt;0, TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Build</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Cumulative_Discount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Cumulative Discount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Cumulative_List_Price__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Cumulative List Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Cumulative_Sales_Price__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Cumulative Sales Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Discount__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Discount(%)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Hours__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Quantity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_List_Price__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show List Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Sales_Price__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Sales Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Special_Terms__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Special Terms</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteDocumentController.cls
public with sharing class QuoteDocumentController {
    public Quote quote{set;get;}
    public List<QuoteLineItem> quoteLineItems{set;get;}

    public QuoteDocumentController(ApexPages.StandardController controller) 
    {
     
        try
        {
            controller.addFields(new String[]{'Id', 'Name', 'Phone', 'Email', 'Subtotal', 'Build__c','Discount','ExpirationDate','QuoteNumber','Total_Discount__c','CreatedDate',
                  'Contact.Name','Contact.MailingCity','Contact.MailingCountry','Contact.MailingPostalCode','Contact.MailingStreet',
                  'Show_List_Price__c','Show_Sales_price__c','Show_Discount__c','Show_Special_Terms__c','Show_Cumulative_List_Price__c','Show_Cumulative_Discount__c','Show_Cumulative_Sales_Price__c','Show_Hours__c',
                  'Opportunity.Owner.Name','Opportunity.Owner.Email','Opportunity.Owner.Phone','Opportunity.OwnerId','Opportunity.CurrencyIsoCode'});
        }
        catch(Exception e){}

        quote =  (Quote) controller.getRecord();
        quoteLineItems = QuoteService.getQuoteLineItems(quote.Id);
    }
}