objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CSDirectorId__c</fullName>
        <formula>Owner.CSDirector__c</formula>
        <label>CS Director Hidden</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CS_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CS Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF(Total_List_Price__c == 0, 0, 1-Amount/Total_List_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NumberOfSites__c</fullName>
        <defaultValue>1</defaultValue>
        <label># of Sites</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Addressable_Revenue__c</fullName>
        <description>This field is a sum of Web (Online), Mobile, Phone, and In-Store Addressable Revenue.</description>
        <formula>Total_Addressable_Web_Online_Rev__c + Total_Addressable_Mobile_Rev__c + Total_Addressable_Phone_Con_Ctr_Rev__c + Total_Addressable_In_Store_Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is a sum of Web (Online), Mobile, Phone, and In-Store Addressable Revenue.  This field should be entered into the pricing calculator.</inlineHelpText>
        <label>Total Addressable Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hours_Info_Only__c</fullName>
        <description>Number of Hours for a services Engagement. This is not a calculated field, but used to capture hours for informational purposes.</description>
        <inlineHelpText>Number of Hours for a services Engagement. This is not a calculated field, but used to capture hours for informational purposes.</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <description>Custom list price for Sales folks to enter</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>POC_Terms__c</fullName>
        <label>Special Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HoursEditable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The hours will be editable when the product is added to opportunity when it&apos;s checked.</description>
        <inlineHelpText>The hours will be editable when the product is added to opportunity when it&apos;s checked.</inlineHelpText>
        <label>Hours Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Integration_Rate__c</fullName>
        <description>The hourly rate for integration services.</description>
        <inlineHelpText>Enter the rate per hour for integration service products.</inlineHelpText>
        <label>Integration Rate</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductSubFamily__c</fullName>
        <label>Product Add-On</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CNET DataSource</fullName>
                </value>
                <value>
                    <fullName>BYOS</fullName>
                </value>
                <value>
                    <fullName>BYO-API</fullName>
                </value>
                <value>
                    <fullName>Monthly API</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 1</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 2</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 3</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 4</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <description>This field categorizes products by license type. Products that are not specific to license type are categorized as Platform.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recommend</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Find</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UseStandardPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The price defined on the standard price book for this product will be used when it&apos;s checked.</inlineHelpText>
        <label>Use Standard Price</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CSDirector__c</fullName>
        <description>Indicates the client services director that should be copied on the 1st level approval email message for opportunities.</description>
        <label>CS Director</label>
        <relationshipName>CSDirector</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler 
{
    /*
    public static void recalculateOpportunityProductQuantity(Map<Id, Opportunity> newOpportunityMap, Map<Id, Opportunity> oldOpportunityMap)
    {
        List<String> opportunityIds = new List<String>();
        Opportunity newOpportunity;
        Opportunity oldOpportunity;
        for(String opportunityId : newOpportunityMap.keySet())
        {
            newOpportunity = newOpportunityMap.get(opportunityId);
            oldOpportunity = oldOpportunityMap.get(opportunityId);

            if(newOpportunity.NumberOfSites__c != oldOpportunity.NumberOfSites__c)
            {
                opportunityIds.add(opportunityId);
            }                
        }

        if(opportunityIds.size() > 0)
        {
            List<OpportunityLineItem> lineItems = 
                [select Opportunity.NumberOfSites__c, Hours_Info_Only__c, PricebookEntry.Product2.Hours__c
                 from OpportunityLineItem
                 where OpportunityId in :opportunityIds 
                 and (PricebookEntry.Product2.Family = 'Integration' or PricebookEntry.Product2.Family = 'Services')
                 and PricebookEntry.Product2.HoursEditable__c = false];

            if(lineItems.size() > 0)
            {
                for(OpportunityLineItem lineItem : lineItems)
                {
                    lineItem.Hours_Info_Only__c = calculateHoursInfo(lineItem.Opportunity.NumberOfSites__c, lineItem.PricebookEntry.Product2.Hours__c);
                }
                Database.update(lineItems, false);
            }
        }
    }
    */
    public static void recalculateOpportunityProductPrice(Map<Id, Opportunity> newOpportunityMap, Map<Id, Opportunity> oldOpportunityMap)
    {
        List<String> opportunityIds = new List<String>();
        Opportunity newOpportunity;
        Opportunity oldOpportunity;
        for(String opportunityId : newOpportunityMap.keySet())
        {
            newOpportunity = newOpportunityMap.get(opportunityId);
            oldOpportunity = oldOpportunityMap.get(opportunityId);

            if(newOpportunity.Total_Addressable_Revenue__c != oldOpportunity.Total_Addressable_Revenue__c)
            {
                opportunityIds.add(opportunityId);
            }                
        }

        if(opportunityIds.size() > 0)
        {
            List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>();
            for(Opportunity opp : [select Total_Addressable_Revenue__c, NumberOfSites__c, CurrencyIsoCode,
                                    (select Id, UnitPrice, List_Price__c, Discount__c, Quantity,
                                            OpportunityId, PricebookEntryId, POC_Terms__c, Hours_Info_Only__c,
                                            PricebookEntry.UnitPrice, PricebookEntry.Product2Id,
                                            PricebookEntry.Product2.UseStandardPrice__c,
                                            PricebookEntry.Product2.Name,
                                            PricebookEntry.Product2.Family, 
                                            PricebookEntry.Product2.HoursEditable__c,
                                            PricebookEntry.Product2.Product_Sub_Category__c,
                                            PricebookEntry.Product2.ProductSubFamily__c,
                                            PricebookEntry.Product2.Hours__c,
                                            PricebookEntry.Product2.Integration_Rate__c
                                    from OpportunityLineItems
                                    order by PricebookEntry.Product2.Family,
                                            PricebookEntry.Product2.Product_Sub_Category__c,
                                            PricebookEntry.Product2.ProductSubFamily__c,
                                            PricebookEntry.Product2.Name)
                                from Opportunity where Id in :opportunityIds])
            
            {
                if(opp.OpportunityLineItems.size() > 0)
                {
                    PriceCalculator.calculatePrice(opp, opp.OpportunityLineItems);
                    lineItems.addAll(opp.OpportunityLineItems);
                }
            }  
            try
            {
                update lineItems;
            }
            catch(Exception ex)
            {
                system.debug(ex);
            }
        }
    }

    public static void setCSDirectorField(List<Opportunity> opportunities)
    {
        for(Opportunity opp : opportunities)
        {
            opp.CS_Director__c = opp.CSDirectorId__c;
        }        
    }

    /*
    private static Decimal calculateHoursInfo(Decimal numberOfSites, Decimal productHours)
    {
        if(productHours != null && numberOfSites != null && numberOfSites > 0)
        {
            return productHours * numberOfSites;
        }
        return productHours;     
    }
    */


    
    /*
    public static void sendApprovalRequest(Map<Id, Opportunity> newOpportunityMap, Map<Id, Opportunity> oldOpportunityMap)
    {
        List<String> opportunityIds = new List<String>();
        Opportunity newOpportunity;
        Opportunity oldOpportunity;
        for(String opportunityId : newOpportunityMap.keySet())
        {
            newOpportunity = newOpportunityMap.get(opportunityId);
            oldOpportunity = oldOpportunityMap.get(opportunityId);

            if(newOpportunity.ApprovalSubmitted__c && !oldOpportunity.ApprovalSubmitted__c)
            {
                opportunityIds.add(opportunityId);
            }                
        }

        if(opportunityIds.size() > 0)
        {
            List<EmailTemplate> templates = [select Id from EmailTemplate where DeveloperName = 'Opportunity_Approval_Submit_Approval'];
            if(templates.size() > 0)
            {
                sendApprovalRequest(opportunityIds, templates[0].Id);
            }            
        }
    }

    private static void sendApprovalRequest(List<String> opportunityIds, String templateId)
    {
        List<User> recipients = getRecipients();
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        For(Opportunity opp : [select Id, Owner.CSDirector__c from Opportunity where Id in :opportunityIds])
        {
            if(opp.Owner.CSDirector__c != null)
            {
                mails.add(initSingleMessage(opp.Id, opp.Owner.CSDirector__c, templateId));
            }            
            for(User u : recipients)
            {
                mails.add(initSingleMessage(opp.Id, u.Id, templateId));
            }
        }

        if(mails.size() > 0)
        {
            Messaging.sendEmail(mails);
        }
    }

    private static List<User> getRecipients()
    {
        return [select Id from User where UserRoleId in (select Id from UserRole where DeveloperName = 'VP_Client_and_Customer_Services')];
    }

    private static Messaging.SingleEmailMessage initSingleMessage(String opportunityId, String userId, String templateId)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(userId);
        mail.setTemplateId(templateId);
        mail.setWhatId(opportunityId);
        mail.setSaveAsActivity(false);
        return mail;        
    }
    */
}