objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF(Total_List_Price__c == 0, 0, 1-Amount/Total_List_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NumberOfSites__c</fullName>
        <defaultValue>1</defaultValue>
        <label># of Sites</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Addressable_Revenue__c</fullName>
        <description>This field is a sum of Web (Online), Mobile, Phone, and In-Store Addressable Revenue.</description>
        <formula>Total_Addressable_Web_Online_Rev__c + Total_Addressable_Mobile_Rev__c + Total_Addressable_Phone_Con_Ctr_Rev__c + Total_Addressable_In_Store_Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is a sum of Web (Online), Mobile, Phone, and In-Store Addressable Revenue.  This field should be entered into the pricing calculator.</inlineHelpText>
        <label>Total Addressable Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Commission_Notes__c</fullName>
        <description>Used to view notes for commissions - Finance Only</description>
        <label>Commission Notes</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Fee</fullName>
                </value>
                <value>
                    <fullName>Time and Materials</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hours_Info_Only__c</fullName>
        <description>Number of Hours for a services Engagement. This is not a calculated field, but used to capture hours for informational purposes.</description>
        <inlineHelpText>Number of Hours for a services Engagement. This is not a calculated field, but used to capture hours for informational purposes.</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <description>Custom list price for Sales folks to enter</description>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Deferral_Release_Date__c</fullName>
        <description>If % Paid out is modified, edit Next Deferral&apos;s release date</description>
        <inlineHelpText>If you modified the % Paid out, make sure to edit the next Deferral&apos;s release date</inlineHelpText>
        <label>Next Deferral Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POC_Terms__c</fullName>
        <label>Special Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percentage_Paid_Out__c</fullName>
        <defaultValue>1</defaultValue>
        <description>% of commission that will be paid</description>
        <inlineHelpText>% of commission that will be paid</inlineHelpText>
        <label>% Paid Out</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>HoursEditable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The hours will be editable when the product is added to opportunity when it&apos;s checked.</description>
        <inlineHelpText>The hours will be editable when the product is added to opportunity when it&apos;s checked.</inlineHelpText>
        <label>Hours Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Integration_Rate__c</fullName>
        <description>The hourly rate for integration services.</description>
        <inlineHelpText>Enter the rate per hour for integration service products.</inlineHelpText>
        <label>Integration Rate</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductSubFamily__c</fullName>
        <label>Product Add-On</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Sub_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CNET DataSource</fullName>
                </value>
                <value>
                    <fullName>BYOS</fullName>
                </value>
                <value>
                    <fullName>BYO-API</fullName>
                </value>
                <value>
                    <fullName>Monthly API</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 1</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 2</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 3</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 4</fullName>
                </value>
                <value>
                    <fullName>Language Surcharge 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <description>This field categorizes products by license type. Products that are not specific to license type are categorized as Platform.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recommend</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Find</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UseStandardPrice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The price defined on the standard price book for this product will be used when it&apos;s checked.</inlineHelpText>
        <label>Use Standard Price</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <formula>IF(Total_List_Price__c == 0, 0, 1-TotalPrice/Total_List_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Commission_Notes__c</fullName>
        <description>Used to view notes for commissions - Finance Only</description>
        <label>Commission Notes</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractType__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Fee</fullName>
                </value>
                <value>
                    <fullName>Time and Materials</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hours_Info_Only__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Deferral_Release_Date__c</fullName>
        <description>If % Paid out is modified, edit Next Deferral&apos;s release date</description>
        <inlineHelpText>If you modified the % Paid out, make sure to edit the next Deferral&apos;s release date</inlineHelpText>
        <label>Next Deferral Release Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POC_Terms__c</fullName>
        <label>Special Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percentage_Paid_Out__c</fullName>
        <defaultValue>1</defaultValue>
        <description>% of commission that will be paid</description>
        <inlineHelpText>% of commission that will be paid</inlineHelpText>
        <label>% Paid Out</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EditQuoteProductsExtension.cls
public with sharing class EditQuoteProductsExtension 
{    
    public Decimal ConversionRate { get; private set; }
    
    public EditQuoteProductsExtension(ApexPages.StandardController stdController) 
    {
        if(ConversionRate == null)
        {
            Opportunity opp = (Opportunity)stdController.getRecord();
            initConversionRateMap(opp.CurrencyIsoCode);
        }        
    }    
    
    // ContactType__c field select Options
    public String ContractTypeOptions
    {
        get
        {
            JSONGenerator gen = JSON.createGenerator(false);     
            gen.writeStartArray();
            gen.writeStartObject();
            gen.writeStringField('Value', '');
            gen.writeStringField('Label', '--None--');
            gen.writeEndObject();
            Schema.DescribeFieldResult dfr = OpportunityLineItem.ContractType__c.getDescribe();
            for(Schema.PicklistEntry entry : dfr.getPicklistValues())        
            {
                if(entry.isActive())
                {
                    gen.writeStartObject();
                    gen.writeStringField('Value', entry.getValue());
                    gen.writeStringField('Label', entry.getLabel());
                    gen.writeEndObject();
                }
            }      
            gen.writeEndArray();            
            return gen.getAsString();
        }
    }

    // Billingcommitment__c field select Options
    /*public String BillingcommittmentOptions
    {
        get
        {
            JSONGenerator gen = JSON.createGenerator(false);     
            gen.writeStartArray();
            gen.writeStartObject();
            gen.writeStringField('Value', '');
            gen.writeStringField('Label', '--None--');
            gen.writeEndObject();
            Schema.DescribeFieldResult dfr = OpportunityLineItem.Billingcommitment__c.getDescribe();
            for(Schema.PicklistEntry entry : dfr.getPicklistValues())        
            {
                if(entry.isActive())
                {
                    gen.writeStartObject();
                    gen.writeStringField('Value', entry.getValue());
                    gen.writeStringField('Label', entry.getLabel());
                    gen.writeEndObject();
                }
            }      
            gen.writeEndArray();            
            return gen.getAsString();
        }
    }*/

    private void initConversionRateMap(String currencyIsoCode)
    {
        Date today = Date.today();
        List<DatedConversionRate> conversionRates = [select IsoCode, ConversionRate 
                                                     from DatedConversionRate
                                                     where StartDate <= :today and 
                                                           NextStartDate >= :today and
                                                           IsoCode = :currencyIsoCode];
        if(conversionRates.size() > 0)
        {
            ConversionRate = conversionRates[0].ConversionRate;
        }
        else
        {
            ConversionRate = 1;
        }
    }

    @RemoteAction
    public static List<OpportunityLineItem> getOpportunityProducts(String opportunityId)
    {
        Opportunity opp = [select Total_Addressable_Revenue__c, NumberOfSites__c, CurrencyIsoCode,
                                (select Id, UnitPrice, List_Price__c, Discount__c, Quantity,
                                        OpportunityId, PricebookEntryId, POC_Terms__c, Hours_Info_Only__c, ContractType__c,
                                        PricebookEntry.UnitPrice, PricebookEntry.Product2Id,
                                        PricebookEntry.Product2.UseStandardPrice__c,
                                        PricebookEntry.Product2.Name,
                                        PricebookEntry.Product2.Family, 
                                        PricebookEntry.Product2.HoursEditable__c,
                                        PricebookEntry.Product2.Product_Sub_Category__c,
                                        PricebookEntry.Product2.ProductSubFamily__c,
                                        PricebookEntry.Product2.Hours__c,
                                        PricebookEntry.Product2.Integration_Rate__c
                                 from OpportunityLineItems
                                 order by PricebookEntry.Product2.Family,
                                          PricebookEntry.Product2.Product_Sub_Category__c,
                                          PricebookEntry.Product2.ProductSubFamily__c,
                                          PricebookEntry.Product2.Name)
                           from Opportunity where Id = :opportunityId];

        System.debug(opp.OpportunityLineItems);
        PriceCalculator.calculatePrice(opp, opp.OpportunityLineItems);
        System.debug(opp.OpportunityLineItems);
        return opp.OpportunityLineItems;        
    }

    @RemoteAction
    public static List<OpportunityLineItem> addProducts(String opportunityId,
                                                        String addedPricebookEntryIds,
                                                        List<OpportunityLineItem> oldLineItems)
    {
        List<OpportunityLineItem> addedLineItems = getAddedLineItems(opportunityId, addedPricebookEntryIds);
        if(oldLineItems == null || oldLineItems.size() == 0)
        {
            return addedLineItems;
        }
        else
        {
            return mergeLineItems(oldLineItems, addedLineItems);
        }
    }

    @RemoteAction
    public static void save(String opportunityId, List<OpportunityLineItem> lineItems)
    {
        Opportunity opp = [select Id, Name, AccountId, CurrencyIsoCode, Pricebook2Id, SyncedQuoteID
                            from Opportunity where Id = :opportunityId];
        
        Savepoint sp = Database.setSavepoint();
        try
        {
            // stop sync with the old quote
            stopQuoteSync(opp);

            upsert lineItems;
            System.debug(lineItems);

            Quote newQuote = createQuote(opp, lineItems);

            syncQuote(opp, newQuote.Id);     
        } 
        catch(Exception ex)
        {
            throw new CustomException(ex.getDmlMessage(0).unescapeHtml4(), ex);     
        }      
    }

    private static List<OpportunityLineItem> getAddedLineItems(String opportunityId, String addedPricebookEntryIds)
    {
        List<OpportunityLineItem> addedLineItems = new List<OpportunityLineItem>();

        Opportunity opp = [select Total_Addressable_Revenue__c, NumberOfSites__c, CurrencyIsoCode
                           from Opportunity where Id = :opportunityId];

        List<String> pricebookEntryIds = addedPricebookEntryIds.split(';'); 
        for(PricebookEntry entry : [select Id, Product2Id, UnitPrice, Product2.Name,
                                           Product2.Family, Product2.Product_Sub_Category__c,
                                           Product2.ProductSubFamily__c, Product2.Hours__c,
                                           Product2.Integration_Rate__c, 
                                           Product2.UseStandardPrice__c,
                                           Product2.HoursEditable__c
                                    from PricebookEntry where Id in :pricebookEntryIds])
        {
            Decimal hours = getDefaultHours(entry.Product2.Hours__c, opp.NumberOfSites__c, entry.Product2.Family);            
            addedLineItems.add(new OpportunityLineItem(OpportunityId = opportunityId,
                                                       PricebookEntry = entry,
                                                       PricebookEntryId = entry.Id,
                                                       List_Price__c = 0,
                                                       //UnitPrice = 0,
                                                       Discount__c = 0,
                                                       Quantity = 1,
                                                       Hours_Info_Only__c = hours));
        }          
        PriceCalculator.calculatePrice(opp, addedLineItems);
        return addedLineItems;
    }

    private static Decimal getDefaultHours(Decimal productHours, Decimal numberOfSites, String family)
    {
        if(family != 'Integration' && family != 'Services')
        {
            return productHours;
        }
        // Based on Julie's response on 10/18/2016, the NumberofSites should not
        // be included in the pricing calculation.
        /*if(productHours != null && numberOfSites != null && numberOfSites > 0)
        {
            return productHours * numberOfSites;
        }*/
        return productHours;     
    }

    private static List<OpportunityLineItem> mergeLineItems(List<OpportunityLineItem> oldLineItems, List<OpportunityLineItem> addedLineItems)
    {
        oldLineItems.addAll(addedLineItems);
        Map<String, Map<String, List<OpportunityLineItem>>> lineItemMap = getLineItemMap(oldLineItems);
        List<OpportunityLineItem> newLineItems = new List<OpportunityLineItem>();
        for(String category : lineItemMap.keySet())
        {
            for(String subCategory : lineItemMap.get(category).keySet())
            {
                newLineItems.addAll(lineItemMap.get(category).get(subCategory));
            }
        }
        return newLineItems;
    }

    private static Map<String, Map<String, List<OpportunityLineItem>>> getLineItemMap(List<OpportunityLineItem> lineItems)
    {
        Map<String, Map<String, List<OpportunityLineItem>>> lineItemMap = new Map<String, Map<String, List<OpportunityLineItem>>>();
        String category;
        String subCategory;
        for(OpportunityLineItem lineItem : lineItems)
        {
            category = lineItem.PricebookEntry.Product2.Family;
            subCategory = lineItem.PricebookEntry.Product2.Product_Sub_Category__c;            
            if(!lineItemMap.containsKey(category))
            {
                lineItemMap.put(category, new Map<String, List<OpportunityLineItem>>());
            }
            if(!lineItemMap.get(category).containsKey(subCategory))
            {
                lineItemMap.get(category).put(subCategory, new List<OpportunityLineItem>());
            }
            lineItemMap.get(category).get(subCategory).add(lineItem);
        }
        return lineItemMap;
    }

    private static void stopQuoteSync(Opportunity opp)
    {
        if(opp.Pricebook2Id == null)
        {
            opp.Pricebook2Id = [select Id from Pricebook2 where IsStandard = true].Id;
        }
        opp.SyncedQuoteID = null;
        update opp;
    }

    private static Quote createQuote(Opportunity opp, List<OpportunityLineItem> lineItems)
    {        
        Quote newQuote = new Quote(OpportunityId = opp.Id,
                                   Name = opp.Name,
                                   Pricebook2Id = opp.Pricebook2Id);
        insert newQuote;

        system.debug('newQuote: ' + newQuote);

        List<QuoteLineItem> quoteItems = new List<QuoteLineItem>();
        for(OpportunityLineItem lineItem : lineItems)
        {
            quoteItems.add(new QuoteLineItem(QuoteId = newQuote.Id,
                                             PricebookEntryId = lineItem.PricebookEntryId,
                                             Quantity = lineItem.Quantity,
                                             UnitPrice = lineItem.UnitPrice,
                                             List_Price__c = lineItem.List_Price__c,
                                             POC_Terms__c = lineItem.POC_Terms__c,
                                             Discount__c = lineItem.Discount__c,
                                             Hours_Info_Only__c = lineItem.Hours_Info_Only__c,
                                             //adding in % Paid Out field
                                             Percentage_Paid_Out__c = lineItem.Percentage_Paid_Out__c,
                                             //adding Next Deferral Date and Commission Notes Fields
                                             Commission_Notes__c = lineItem.Commission_Notes__c,
                                             Next_Deferral_Release_Date__c = lineItem.Next_Deferral_Release_Date__c,
                                             //adding ContractType__c and Billingcommitment__c fields
                                             ContractType__c = lineItem.ContractType__c
                                             //Billingcommitment__c = lineItem.Billingcommitment__c
                                             ));
        }

        system.debug('quoteItems: ' + quoteItems);
        if(quoteItems.size() > 0)
        {
            insert quoteItems;
        }        

        return newQuote;
    }

    private static void syncQuote(Opportunity opp, String quoteId)
    {
        opp.SyncedQuoteID = quoteId;
        update opp;
    }
}