objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Sub_Category__c</fullName>
        <description>This field categorizes products by license type. Products that are not specific to license type are categorized as Platform.</description>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recommend</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Find</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>CDP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Hours_Info_Only__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name for the roll-up fields on Quote in order to populate the Sales Order Form</description>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POC_Terms__c</fullName>
        <label>Special Terms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteService.cls
public class QuoteService 
{
    public static list<QuoteLineItem> getQuoteLineItems(String quoteId)
    {
        List<QuoteLineItem> quoteLineItems = [select Id, Name__c,TotalPrice, UnitPrice, Quantity, ListPrice, Subtotal,Discount__c, 
                                              Discount,Hours_Info_Only__c, List_Price__c,POC_Terms__c,
                                              PricebookEntry.Product2.Name, PricebookEntry.Product2Id, PricebookEntry.Product2.Hours__c,
                                              PricebookEntry.Product2.Family, PricebookEntry.Product2.Product_Sub_Category__c 
                                              from QuoteLineItem where QuoteId = :quoteId order by PricebookEntry.Product2.Family, 
                                              PricebookEntry.Product2.Product_Sub_Category__c, PricebookEntry.Product2.Name];
        return quoteLineItems;        
    }
}